package globals

const (
	DEFAULT_GUI_SVG_PATH = "gui/src/"
	TASK_HAVE_SVG_PATH = DEFAULT_GUI_SVG_PATH + "briefcase.svg"
	TASK_NICE_SVG_PATH = DEFAULT_GUI_SVG_PATH + "mug.svg"
	TASK_SHOULD_SVG_PATH = DEFAULT_GUI_SVG_PATH + "gears.svg"
	TASK_LIKE_SVG_PATH = DEFAULT_GUI_SVG_PATH + "seedling.svg"
	TASK_SPECIAL_GOOD_SVG_PATH = DEFAULT_GUI_SVG_PATH + "medal.svg"
	TASK_SPECIAL_BAD_SVG_PATH = DEFAULT_GUI_SVG_PATH + "bugs.svg"
)
